ALTER TABLE `invoices` CHANGE NO INVOICE_NUMBER varchar(100) NULL COMMENT 'numer faktury';
ALTER TABLE `invoices` CHANGE INV_DATE INVOICE_DATE  date DEFAULT NULL COMMENT 'data wystawienia';
ALTER TABLE `invoices` CHANGE `DESC` DESCRIPTION varchar(255)  DEFAULT NULL;
ALTER TABLE `invoices` CHANGE input_time INPUT_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE firms CHANGE `DESC` DESCRIPTION varchar(100) NULL;